
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # Раскомментируйте следующие строки, если нужно связать с контейнером бэкенда
    # networks:
    #   - app-network
    
# Раскомментируйте, если ваш бэкенд находится в той же сети Docker
networks:
  app-network:
    external: true
